# The URL the site will be built for
base_url = "https://imflog.github.io"
title = "My personal blog"

ignored_content = ["README.md"]

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true
# Them chose
theme = "DeepThought"

taxonomies = [
    { name = "categories", feed = true, paginate_by = 10 },
    { name = "tags", fees = true, paginate_by = 10 },
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
navbar_items = [
    { code = "en", nav_items = [
        { url = "$BASE_URL/", name = "Home" },
        { url = "$BASE_URL/posts", name = "Posts" },
    ]},
]
mermaid.enabled = true

[extra.author]
name = "Florian Garcia"
avatar = "/images/avatar.png"

[extra.social]
email = "garcia.florian.perso@gmail.com"
twitter = "im_flog"
github = "imFlog"
linkedin = "garciaflorian"
mastodon_username = "ImFlog"
mastodon_server = "fosstodon.org"